#!/bin/bash

# USER DEFINED CONSTANTS

SERVER_ADDRESS=USER@ADDRESS 
SERVER_FOLDER_LOCATION=$(cd $(dirname "$0") && pwd)/server
    # You can change this to whatever you want but if you store it in the same location
        # server and client side then this will save you some time
CLIENT_FOLDER_LOCATION=$(cd $(dirname "$0") && pwd)
    # If you would like to hard code this you can but it should fine the location of this script


# EXPORTING THOSE CONSTANTS 

export CLIENT_FOLDER_LOCATION
export SERVER_ADDRESS 
export SERVER_FOLDER_LOCATION
